-- schema.sql
CREATE DATABASE IF NOT EXISTS eepd CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE eepd;

CREATE TABLE tb_usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  tipo ENUM('admin','professor','aluno') NOT NULL DEFAULT 'admin',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_professores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  disciplina VARCHAR(150),
  foto VARCHAR(255),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_alunos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  turma VARCHAR(50),
  foto VARCHAR(255),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  resumo VARCHAR(500),
  conteudo TEXT,
  imagem VARCHAR(255),
  data_publicacao DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_contato (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  assunto VARCHAR(255),
  mensagem TEXT,
  recebido_em DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_carrossel (
  id INT AUTO_INCREMENT PRIMARY KEY,
  imagem VARCHAR(255) NOT NULL
);